const Anthropic = require('@anthropic-ai/sdk');
const { Octokit } = require('@octokit/rest');
const fs = require('fs');

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const GITHUB_TOKEN      = process.env.GITHUB_TOKEN;
const REPO_OWNER        = process.env.REPO_OWNER;
const REPO_NAME         = process.env.REPO_NAME;
const ISSUE_NUMBER      = process.env.ISSUE_NUMBER;
const ISSUE_TITLE       = process.env.ISSUE_TITLE;
const ISSUE_BODY        = process.env.ISSUE_BODY;

const FILES = {
  'public/index.html': fs.readFileSync('./public/index.html', 'utf8'),
  'src/server.js':     fs.readFileSync('./src/server.js', 'utf8')
};

const anthropic = new Anthropic({ apiKey: ANTHROPIC_API_KEY });
const octokit   = new Octokit({ auth: GITHUB_TOKEN });

async function run() {
  console.log(`[AGENT] Starting for Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}`);

  console.log('[AGENT] Calling Claude API...');
  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 8096,
    messages: [{
      role: 'user',
      content: `You are a senior frontend/backend developer working on QuickBite — a professional food order tracking web application.

GitHub Issue Title: ${ISSUE_TITLE}
GitHub Issue Description: ${ISSUE_BODY || 'No description provided.'}

Current files:

--- FILE: public/index.html ---
${FILES['public/index.html']}

--- FILE: src/server.js ---
${FILES['src/server.js']}

Instructions:
- Analyze the issue carefully
- Make ONLY the changes needed to fulfill the issue
- Keep the professional look and feel of the app intact
- Return your response in EXACTLY this format (no extra text before or after):

FILE: public/index.html
<complete updated file content, or write UNCHANGED if no modification needed>

FILE: src/server.js
<complete updated file content, or write UNCHANGED if no modification needed>`
    }]
  });

  const raw = response.content[0].text.trim();
  console.log('[AGENT] Claude responded');

  const filesToUpdate = {};
  const htmlMatch   = raw.match(/FILE: public\/index\.html\n([\s\S]*?)(?=\nFILE: src\/server\.js|$)/);
  const serverMatch = raw.match(/FILE: src\/server\.js\n([\s\S]*?)$/);

  if (htmlMatch   && htmlMatch[1].trim()   !== 'UNCHANGED') filesToUpdate['public/index.html'] = htmlMatch[1].trim();
  if (serverMatch && serverMatch[1].trim() !== 'UNCHANGED') filesToUpdate['src/server.js']     = serverMatch[1].trim();

  if (Object.keys(filesToUpdate).length === 0) {
    console.log('[AGENT] No changes needed');
    return;
  }

  console.log(`[AGENT] Files to update: ${Object.keys(filesToUpdate).join(', ')}`);

  const { data: refData } = await octokit.git.getRef({ owner: REPO_OWNER, repo: REPO_NAME, ref: 'heads/main' });
  const mainSHA = refData.object.sha;

  const branchName = `fix/issue-${ISSUE_NUMBER}-agent`;
  console.log(`[AGENT] Creating branch: ${branchName}`);
  await octokit.git.createRef({ owner: REPO_OWNER, repo: REPO_NAME, ref: `refs/heads/${branchName}`, sha: mainSHA });

  for (const [filePath, newContent] of Object.entries(filesToUpdate)) {
    const { data: fileData } = await octokit.repos.getContent({ owner: REPO_OWNER, repo: REPO_NAME, path: filePath, ref: 'main' });
    await octokit.repos.createOrUpdateFileContents({
      owner: REPO_OWNER, repo: REPO_NAME,
      path: filePath,
      message: `fix: AI agent resolves #${ISSUE_NUMBER} — ${ISSUE_TITLE}`,
      content: Buffer.from(newContent).toString('base64'),
      sha: fileData.sha,
      branch: branchName
    });
    console.log(`[AGENT] Committed: ${filePath}`);
  }

  const { data: pr } = await octokit.pulls.create({
    owner: REPO_OWNER, repo: REPO_NAME,
    title: `fix: resolves #${ISSUE_NUMBER} — ${ISSUE_TITLE}`,
    head: branchName, base: 'main',
    body: `## AI Agent Generated PR\n\n**Resolves:** #${ISSUE_NUMBER}\n**Issue:** ${ISSUE_TITLE}\n**Files changed:** ${Object.keys(filesToUpdate).join(', ')}\n\n---\n> Auto-generated by Claude AI. Please review before merging.`
  });

  console.log(`[AGENT] ✅ PR raised: ${pr.html_url}`);
}

run().catch(err => {
  console.error('[AGENT] ❌ Error:', err.message);
  process.exit(1);
});
